name: Changelog Generation

on:
  workflow_dispatch: # Manual trigger only

jobs:
  send_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history is fetched to access all commits

      - name: Read Last Commit Hash from .last_commit
        run: |
          if [ -f .last_commit ]; then
            LAST_COMMIT_HASH=$(cat .last_commit)
          else
            LAST_COMMIT_HASH=$(git rev-list --max-parents=0 HEAD)  # Use first commit if no record
          fi
          echo "LAST_COMMIT_HASH=$LAST_COMMIT_HASH" >> $GITHUB_ENV

      - name: Generate Changelog
        run: |
          echo "## Changelog from Commit $LAST_COMMIT_HASH to $(git rev-parse HEAD)" > changelog.md
          echo "" >> changelog.md

          declare -A commit_types=( 
            [feat]="🚀 Features"
            [fix]="🛠 Fixes"
            [perf]="⚡ Performance Improvements"
            [refactor]="♻️ Refactoring"
            [docs]="📝 Documentation Updates"
            [style]="🎨 Code Style Changes"
            [test]="🧪 Tests"
            [build]="🏗️ Build Changes"
            [ci]="🔧 CI/CD"
            [chore]="🔨 Miscellaneous"
            [revert]="⏪ Reverts"
            [release]="🚀 Release Updates"
            [workflow]="⚙️ Workflow Changes"
          )

          HAS_CHANGES=0  # Track if we have at least one section

          for type in "${!commit_types[@]}"; do
            section=${commit_types[$type]}
            commits=$(git log $LAST_COMMIT_HASH..HEAD --grep="^$type:" --pretty=format:"- %h %s (%an, %ad)" --date=format:'%Y-%m-%d %H:%M')

            if [ -n "$commits" ]; then
              echo "### $section" >> changelog.md
              echo "$commits" >> changelog.md
              echo "" >> changelog.md
              HAS_CHANGES=1
            fi
          done

          if [ "$HAS_CHANGES" -eq 0 ]; then
            echo "No relevant commits found for this release. Exiting."
            exit 0
          fi

      - name: Update HISTORY.md
        run: |
          echo "## Changelog for Version $VERSION" >> HISTORY.md
          echo "" >> HISTORY.md
          cat changelog.md >> HISTORY.md
