name: Publish to PyPI

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from file
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine build

      - name: Build package inside Manylinux Docker
        run: |
          docker run --rm -v $(pwd):/project quay.io/pypa/manylinux2014_x86_64 \
          /bin/bash -c "
            cd /project &&
            /opt/python/cp39-cp39/bin/python -m pip install --upgrade pip &&
            /opt/python/cp39-cp39/bin/python -m pip install setuptools wheel auditwheel &&
            /opt/python/cp39-cp39/bin/python -m build &&
            auditwheel repair dist/*.whl -w wheelhouse/
          "

      - name: Create Git tag
        run: |
          git config --global user.email "mukulwaval@example.com"
          git config --global user.name "MukulWaval"
          if ! git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            git tag "v${{ env.VERSION }}"
            git push origin "v${{ env.VERSION }}"
          else
            echo "Tag v${{ env.VERSION }} already exists. Skipping tagging."
          fi

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
        run: twine upload wheelhouse/*.whl --verbose
