name: Test

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel cmake pybind11 pytest

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Build package
        run: |
          python3 setup.py sdist bdist_wheel --universal

      - name: Install Aethermark
        run: |
          pip install --force-reinstall --no-cache-dir dist/aethermark-*.tar.gz

      - name: Run tests
        run: pytest
